--- #YAML:1.0
name:                Compress-Raw-Zlib
version:             2.004
abstract:            Low-Level Interface to zlib compression library
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Paul Marquess <pmqs@cpan.org>
